version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      MIX_ENV: dev
      DB_USERNAME: root
      DB_PASSWORD: ""
      DB_NAME: tienda4
      DB_HOST: db
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: tienda4
    volumes:
      - db_data:/var/lib/mysql

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_data:
  jenkins_home:
